// <auto-generated />
using System;
using Bitmex.Client.Websocket.EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreSqlite.Migrations.BitmexBookDb
{
    [DbContext(typeof(BitmexBookDbContext))]
    [Migration("20181211134019_BitmexBookDb")]
    partial class BitmexBookDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Bitmex.Client.Websocket.EFCoreSqlite.BookLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Price");

                    b.Property<string>("Side");

                    b.Property<long?>("Size");

                    b.Property<string>("Symbol");

                    b.HasKey("Id");

                    b.ToTable("BookLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
