// <auto-generated />
using System;
using EFCoreSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreSqlite.Migrations
{
    [DbContext(typeof(LiquidationContext))]
    partial class LiquidationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("EFCoreSqlite.Liquidation", b =>
                {
                    b.Property<string>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("Price");

                    b.Property<string>("Side");

                    b.Property<string>("Symbol");

                    b.Property<long?>("leavesQty");

                    b.HasKey("OrderID");

                    b.ToTable("Liquidations");
                });
#pragma warning restore 612, 618
        }
    }
}
